### ISSUE TITLE
getting this error

### ISSUE THREAD

**Issue by somiyaa** [chestnut3108/SENTIMENT-ANALYSIS-ON-AUDIO#2]
raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 3

how can i fix this ?

**Comment by shivam-singhl** [comment]
This is because you are using python 2 for loading the pickle files that were made on python 3:-

[https://stackoverflow.com/questions/25843698/valueerror-unsupported-pickle-protocol-3-python2-pickle-can-not-load-the-file/25843801](url)

So to fix this either use python 3 or you can make your own pickle files using the classifier.py script
run the command `python classifier.py` and it will create pickle files according to your python.
